name: CLI Review

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  cli-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Continue CLI Review
        run: |
          echo "Running Continue CLI with prompt:"
          echo "=================================="
          cat review_prompt.txt
          echo "=================================="
          echo ""

          # Run the CLI with the generated prompt and output text directly
          cat review_prompt.txt | cn --config "${{ inputs.assistant }}" -p
        env:
          CONTINUE_API_KEY: ${{ secrets.CONTINUE_API_KEY }}