name: Continue Detailed Review

on:
  pull_request:
    types: [opened, ready_for_review]
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  detailed-code-review:
    name: Continue Detailed Review
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Run Detailed PR Review
        uses: continuedev/continue/actions/detailed-review@381ef1c2d1d79495bf12d3db2b6a0bf4b93c62ff
        with:
          continue-api-key: ${{ secrets.CONTINUE_API_KEY }}
          continue-org: continuedev
          continue-config: continuedev/review-bot
