name: Build Extension on Main

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build-vscode-extension.yml
    with:
      platforms: |
        [
          {
            "os": "ubuntu-latest",
            "platform": "linux",
            "arch": "x64",
            "npm_config_arch": "x64"
          },
          {
            "os": "macos-latest",
            "platform": "darwin",
            "arch": "x64",
            "npm_config_arch": "x64"
          }
        ]
      pre-release: false
      commit-id: ${{ github.sha }}
    secrets: inherit