name: Build Extension on Main

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build-vscode-extension.yml
    with:
      # Uses default platforms (all supported platforms)
      pre-release: false
      commit-sha: ${{ github.sha }}
    secrets: inherit