# When none of the paths are matched for the pr_checks.yaml workflow
# we still need the require-all-checks-to-pass job to pass
name: PR checks skip

on:
  pull_request:
    branches:
      - main
    paths:
      - docs/**

  push:
    branches:
      - main
    paths:
      - docs/**

jobs:
  require-all-checks-to-pass:
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          allowed-failures:
          allowed-skips:
          jobs: []
