name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18, 20, 22, 24]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
        env:
          DEBUG_CLI_TESTS: "1"

      - name: Show test logs on failure (Windows)
        if: failure() && runner.os == 'Windows'
        run: |
          echo "=== Node.js version ==="
          node --version
          echo "=== NPM version ==="
          npm --version
          echo "=== Working directory ==="
          pwd
          echo "=== dist/index.js exists? ==="
          if (Test-Path dist/index.js) { echo "Yes" } else { echo "No" }
          echo "=== First 10 lines of dist/index.js ==="
          if (Test-Path dist/index.js) { Get-Content dist/index.js -First 10 }
        shell: pwsh

      - name: Run linting
        run: npm run lint

      - name: Build
        run: npm run build

  # GitHub does not have a way of requiring that all checks pass (you must manually select each job)
  # This action at least lets us manage the list of required tests via source control
  # so that creators of new jobs can add them to this list
  require-all-checks-to-pass:
    if: always()
    runs-on: ubuntu-latest
    needs:
      - test

    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
