name: PR checks

on:
  pull_request:
    branches:
      - main
    paths:
      - "extensions/vscode/**"
      - "core/**"
      - "gui/**"
      - ".github/workflows**"

jobs:
  vscode-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - uses: actions/cache@v3
        with:
          path: |
            node_modules
            extensions/vscode/node_modules
          key: ${{ runner.os }}-node-vscode-${{ hashFiles('package-lock.json', 'extensions/vscode/package-lock.json') }}

      - name: Install dependencies
        run: |
          npm ci
          cd extensions/vscode
          npm ci
        env:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}

      - name: Type check and lint
        run: |
          cd extensions/vscode
          npx tsc --noEmit
          npm run lint

  core-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - uses: actions/cache@v3
        with:
          path: |
            node_modules
            core/node_modules
          key: ${{ runner.os }}-node-core-${{ hashFiles('package-lock.json', 'core/package-lock.json') }}

      - name: Install dependencies
        run: |
          npm ci
          cd core
          npm ci

      - name: Type check and lint
        run: |
          cd core
          npx tsc --noEmit
          npm run lint
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

  gui-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - uses: actions/cache@v3
        with:
          path: |
            node_modules
            gui/node_modules
          key: ${{ runner.os }}-node-gui-${{ hashFiles('package-lock.json', 'gui/package-lock.json') }}

      - name: Install dependencies
        run: |
          npm ci
          cd gui
          npm ci

      - name: Type check
        run: |
          cd gui
          npx tsc --noEmit

  binary-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - uses: actions/cache@v3
        with:
          path: |
            node_modules
            binary/node_modules
          key: ${{ runner.os }}-node-binary-${{ hashFiles('package-lock.json', 'binary/package-lock.json') }}

      - name: Install dependencies
        run: |
          npm ci
          cd binary
          npm ci

      - name: Type check
        run: |
          cd binary
          npx tsc --noEmit

  tests:
    needs: [vscode-checks, core-checks, gui-checks, binary-checks]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - uses: actions/cache@v3
        with:
          path: |
            node_modules
            extensions/vscode/node_modules
            core/node_modules
            gui/node_modules
          key: ${{ runner.os }}-node-tests-${{ hashFiles('package-lock.json', '**/package-lock.json') }}

      - name: Install dependencies
        run: |
          npm ci
          cd extensions/vscode && npm ci
          cd ../core && npm ci
          cd ../gui && npm ci
        env:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}

      - name: Install and setup Xvfb
        run: |
          sudo apt-get install -y xvfb
          Xvfb :99 &
          export DISPLAY=:99

      - name: Run VSCode e2e tests
        run: |
          cd extensions/vscode
          npm run package
          npm run e2e:ci

      - name: Run core tests
        run: |
          cd core
          npm test

      - name: Run gui tests
        run: |
          cd gui
          npm test
