name: Continue CLI Review

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-continue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Build Continue CLI from source
        run: |
          npm ci
          npm run build

      - name: Run Continue CLI
        run: npm run start -- --config nate/default-assistant -p "Please review the last changes to this codebase and provide some feedback. Then, if the changes had problems that indicate they should not be merged into production, then please call the 'exit' tool to fail the GitHub Action."
        env:
          CONTINUE_API_KEY: ${{ secrets.CONTINUE_API_KEY }}
