name: "Label stale issues and PRs"
on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        assignee: [sestinj, Patrick-Erichsen, tomasz-stefaniak, RomneyDa]
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: "This issue hasn't been updated in a while. @${{ matrix.assignee }} can you take a look?"
          stale-pr-message: "This PR hasn't been updated in a while. @${{ matrix.assignee }} can you take a look?"
          days-before-stale: 180
          days-before-close: -1
          days-before-pr-close: -1
          stale-issue-label: "stale"
          stale-pr-label: "stale"
          debug-only: true
          exempt-issue-labels: "needs-triage,no-stale"
          exempt-pr-labels: "no-stale,no-stale"
          exempt-assignees: ${{ toJSON(fromJSON('["sestinj", "Patrick-Erichsen", "tomasz-stefaniak", "RomneyDa"]').filter(user => user != matrix.assignee)) }}
