name: "Label stale issues and PRs"
on:
  push:
    branches:
      - nate/stale-issue-helper
  schedule:
    - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          close-issue-message: "This issue was closed because it hasn't been updated for 120 days. If it's still important, please reopen + comment and we will glady take another look."
          stale-issue-message: "It looks like this issue hasn't been updated in 90 days. If there's still no activity after 120 days, it will be closed."
          days-before-stale: 90
          days-before-close: 120
          stale-issue-label: "stale"
          stale-pr-label: "stale"
          debug-only: true
          exempt-issue-labels: "needs-triage,no-stale"
          exempt-pr-labels: "no-stale"
